"""Auto-generate LaTeX tables from results, so the paper's TODO tables fill
themselves once the matrix has run.

    python scripts/make_tables.py     # -> paper/tables_auto.tex

Reads outputs/matrix_results.json (or scans outputs/*/results.json) for the main
results table, and results/tokenizer_metrics.json for the motivation table.
"""
import json
from pathlib import Path

import _bootstrap  # noqa: F401

from aggregate import load_cells, summarize  # reuse the aggregation logic
from src.utils import get_logger

logger = get_logger()
SEG_ORDER = ["native", "whitespace", "morphological", "morphological-zeyrek", "char"]


def main_results_table(table: dict) -> str:
    # group key is "model / segmentation"
    by_model: dict[str, dict[str, dict]] = {}
    for key, metrics in table.items():
        model, seg = [s.strip() for s in key.split("/")]
        by_model.setdefault(model, {})[seg] = metrics

    def cell(m, metric):
        if metric not in m:
            return "--"
        return f"{m[metric]['mean']:.3f}$\\pm${m[metric]['std']:.3f}"

    lines = [
        "% Auto-generated by scripts/make_tables.py — paste into tab:main",
        "\\begin{tabular}{llccc}", "\\toprule",
        "Encoder & Segmentation & Intent Acc & Slot F1 & Frame Acc \\\\", "\\midrule",
    ]
    for model in sorted(by_model):
        segs = [s for s in SEG_ORDER if s in by_model[model]]
        segs += [s for s in by_model[model] if s not in SEG_ORDER]
        for i, seg in enumerate(segs):
            m = by_model[model][seg]
            prefix = f"\\multirow{{{len(segs)}}}{{*}}{{{model}}}" if i == 0 else ""
            lines.append(
                f"{prefix} & {seg} & {cell(m,'intent_acc')} & {cell(m,'slot_f1')} "
                f"& {cell(m,'frame_acc')} \\\\"
            )
        lines.append("\\midrule")
    lines[-1] = "\\bottomrule"
    lines.append("\\end{tabular}")
    return "\n".join(lines)


def tokenizer_table() -> str:
    p = Path("results/tokenizer_metrics.json")
    if not p.exists():
        return "% (run scripts/tokenizer_report.py to generate the tokenizer table)"
    data = json.loads(p.read_text(encoding="utf-8"))["rows"]
    lines = [
        "% Auto-generated — paste into tab:tok",
        "\\begin{tabular}{lccccc}", "\\toprule",
        "Encoder & Fertility & Bound.\\ P & Bound.\\ R & Bound.\\ F1 & Respect \\\\",
        "\\midrule",
    ]
    for name, r in data.items():
        lines.append(
            f"{name} & {r['fertility']} & {r['boundary_P']} & {r['boundary_R']} "
            f"& {r['boundary_F1']} & {r['morpheme_respect']} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines)


def main():
    cells = load_cells("outputs/matrix_results.json")
    out = ["% === Auto-generated LaTeX tables (do not hand-edit) ===\n"]
    if cells:
        out.append("%% Main results (tab:main)\n" + main_results_table(summarize(cells)))
    else:
        out.append("% No matrix results yet — run scripts/run_matrix.py first.")
    out.append("\n\n%% Tokenizer metrics (tab:tok)\n" + tokenizer_table())

    Path("paper").mkdir(exist_ok=True)
    Path("paper/tables_auto.tex").write_text("\n".join(out) + "\n", encoding="utf-8")
    print("\n".join(out))
    logger.info("Wrote paper/tables_auto.tex")


if __name__ == "__main__":
    main()
